// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/services/v1/services.proto

package servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerOneService_License_FullMethodName        = "/playerone.services.v1.PlayerOneService/License"
	PlayerOneService_LicenseRelease_FullMethodName = "/playerone.services.v1.PlayerOneService/LicenseRelease"
	PlayerOneService_Register_FullMethodName       = "/playerone.services.v1.PlayerOneService/Register"
)

// PlayerOneServiceClient is the client API for PlayerOneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerOneServiceClient interface {
	License(ctx context.Context, in *LicenseRequest, opts ...grpc.CallOption) (*LicenseResponse, error)
	LicenseRelease(ctx context.Context, in *LicenseReleaseRequest, opts ...grpc.CallOption) (*LicenseReleaseResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type playerOneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerOneServiceClient(cc grpc.ClientConnInterface) PlayerOneServiceClient {
	return &playerOneServiceClient{cc}
}

func (c *playerOneServiceClient) License(ctx context.Context, in *LicenseRequest, opts ...grpc.CallOption) (*LicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseResponse)
	err := c.cc.Invoke(ctx, PlayerOneService_License_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerOneServiceClient) LicenseRelease(ctx context.Context, in *LicenseReleaseRequest, opts ...grpc.CallOption) (*LicenseReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseReleaseResponse)
	err := c.cc.Invoke(ctx, PlayerOneService_LicenseRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerOneServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PlayerOneService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerOneServiceServer is the server API for PlayerOneService service.
// All implementations should embed UnimplementedPlayerOneServiceServer
// for forward compatibility.
type PlayerOneServiceServer interface {
	License(context.Context, *LicenseRequest) (*LicenseResponse, error)
	LicenseRelease(context.Context, *LicenseReleaseRequest) (*LicenseReleaseResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedPlayerOneServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerOneServiceServer struct{}

func (UnimplementedPlayerOneServiceServer) License(context.Context, *LicenseRequest) (*LicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method License not implemented")
}
func (UnimplementedPlayerOneServiceServer) LicenseRelease(context.Context, *LicenseReleaseRequest) (*LicenseReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseRelease not implemented")
}
func (UnimplementedPlayerOneServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPlayerOneServiceServer) testEmbeddedByValue() {}

// UnsafePlayerOneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerOneServiceServer will
// result in compilation errors.
type UnsafePlayerOneServiceServer interface {
	mustEmbedUnimplementedPlayerOneServiceServer()
}

func RegisterPlayerOneServiceServer(s grpc.ServiceRegistrar, srv PlayerOneServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlayerOneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerOneService_ServiceDesc, srv)
}

func _PlayerOneService_License_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerOneServiceServer).License(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerOneService_License_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerOneServiceServer).License(ctx, req.(*LicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerOneService_LicenseRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerOneServiceServer).LicenseRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerOneService_LicenseRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerOneServiceServer).LicenseRelease(ctx, req.(*LicenseReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerOneService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerOneServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerOneService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerOneServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerOneService_ServiceDesc is the grpc.ServiceDesc for PlayerOneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerOneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playerone.services.v1.PlayerOneService",
	HandlerType: (*PlayerOneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "License",
			Handler:    _PlayerOneService_License_Handler,
		},
		{
			MethodName: "LicenseRelease",
			Handler:    _PlayerOneService_LicenseRelease_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _PlayerOneService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/v1/services.proto",
}
