// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/services/v1/services.proto

package servicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on RegisterRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RegisterRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Kid

	// no validation rules for Key

	return nil
}

// RegisterRequestValidationError is the validation error returned by
// RegisterRequest.Validate if the designated constraints aren't met.
type RegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRequestValidationError) ErrorName() string { return "RegisterRequestValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRequestValidationError{}

// Validate checks the field values on RegisterResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RegisterResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// RegisterResponseValidationError is the validation error returned by
// RegisterResponse.Validate if the designated constraints aren't met.
type RegisterResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterResponseValidationError) ErrorName() string { return "RegisterResponseValidationError" }

// Error satisfies the builtin error interface
func (e RegisterResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterResponseValidationError{}

// Validate checks the field values on LicenseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *LicenseRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Type

	return nil
}

// LicenseRequestValidationError is the validation error returned by
// LicenseRequest.Validate if the designated constraints aren't met.
type LicenseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseRequestValidationError) ErrorName() string { return "LicenseRequestValidationError" }

// Error satisfies the builtin error interface
func (e LicenseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseRequestValidationError{}

// Validate checks the field values on LicenseResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *LicenseResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetKeys() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LicenseResponseValidationError{
					field:  fmt.Sprintf("Keys[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// LicenseResponseValidationError is the validation error returned by
// LicenseResponse.Validate if the designated constraints aren't met.
type LicenseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseResponseValidationError) ErrorName() string { return "LicenseResponseValidationError" }

// Error satisfies the builtin error interface
func (e LicenseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseResponseValidationError{}

// Validate checks the field values on LicenseReleaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *LicenseReleaseRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Type

	return nil
}

// LicenseReleaseRequestValidationError is the validation error returned by
// LicenseReleaseRequest.Validate if the designated constraints aren't met.
type LicenseReleaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseReleaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseReleaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseReleaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseReleaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseReleaseRequestValidationError) ErrorName() string {
	return "LicenseReleaseRequestValidationError"
}

// Error satisfies the builtin error interface
func (e LicenseReleaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseReleaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseReleaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseReleaseRequestValidationError{}

// Validate checks the field values on LicenseReleaseResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *LicenseReleaseResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// LicenseReleaseResponseValidationError is the validation error returned by
// LicenseReleaseResponse.Validate if the designated constraints aren't met.
type LicenseReleaseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseReleaseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseReleaseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseReleaseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseReleaseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseReleaseResponseValidationError) ErrorName() string {
	return "LicenseReleaseResponseValidationError"
}

// Error satisfies the builtin error interface
func (e LicenseReleaseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseReleaseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseReleaseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseReleaseResponseValidationError{}

// Validate checks the field values on LicenseResponse_Key with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *LicenseResponse_Key) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Kty

	// no validation rules for K

	// no validation rules for Kid

	return nil
}

// LicenseResponse_KeyValidationError is the validation error returned by
// LicenseResponse_Key.Validate if the designated constraints aren't met.
type LicenseResponse_KeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseResponse_KeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseResponse_KeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseResponse_KeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseResponse_KeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseResponse_KeyValidationError) ErrorName() string {
	return "LicenseResponse_KeyValidationError"
}

// Error satisfies the builtin error interface
func (e LicenseResponse_KeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseResponse_Key.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseResponse_KeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseResponse_KeyValidationError{}
